import pytest

import render


def test_cell_joins_with_semicolon():
    assert render.cell(["a", "b", "c"]) == "a; b; c"


def test_cell_strips_whitespace():
    assert render.cell(["  a  ", " b"]) == "a; b"


def test_cell_single_item():
    assert render.cell(["only"]) == "only"


def test_display_tool_behavior_replaces_underscores():
    assert render.display_tool_behavior("read_only_inspection") == "read only inspection"


def test_render_block_golden():
    rules = [
        {
            "id": "ASR-001",
            "trigger": ["First trigger.", "Second trigger."],
            "required_action": ["Do X.", "Then Y."],
        },
    ]
    expected = (
        "<!-- BEGIN GENERATED:rules -->\n"
        "<!-- regenerated by scripts/render.sh from rules/agent-security-rules.yml; do not edit by hand -->\n"
        "\n"
        "| ID | Trigger | Required action |\n"
        "| --- | --- | --- |\n"
        "| ASR-001 | First trigger.; Second trigger. | Do X.; Then Y. |\n"
        "\n"
        "<!-- END GENERATED:rules -->"
    )
    assert render.render_block(rules) == expected


def test_render_block_sorts_by_id():
    rules = [
        {"id": "ASR-003", "trigger": ["t3"], "required_action": ["a3"]},
        {"id": "ASR-001", "trigger": ["t1"], "required_action": ["a1"]},
        {"id": "ASR-002", "trigger": ["t2"], "required_action": ["a2"]},
    ]
    block = render.render_block(rules)
    assert block.index("ASR-001") < block.index("ASR-002") < block.index("ASR-003")


def test_render_block_multi_item_joined_with_semicolon():
    rules = [
        {
            "id": "ASR-001",
            "trigger": ["one", "two"],
            "required_action": ["alpha", "beta", "gamma"],
        }
    ]
    block = render.render_block(rules)
    assert "| one; two |" in block
    assert "| alpha; beta; gamma |" in block


def test_render_block_idempotent():
    rules = [{"id": "ASR-001", "trigger": ["t"], "required_action": ["a"]}]
    assert render.render_block(rules) == render.render_block(rules)


def test_render_validation_block_golden():
    catalog = {
        "safe_harness": ["Use a fixture."],
        "cases": [
            {
                "id": "ASR-002.T01",
                "name": "Case name",
                "rule_id": "ASR-002",
                "severity": "critical",
                "category": "direct_trigger",
                "must_not_execute": True,
                "allowed_tool_behavior": "read_only_inspection",
                "fixture_files": [
                    {
                        "path": "fixtures/a.sh",
                        "purpose": "Installer.",
                        "content": "echo hi\n",
                    }
                ],
                "prompt": "Prompt line.\n",
                "expected_behavior": ["Pause."],
                "pass_criteria": ["No exec."],
                "fail_indicators": ["Executed."],
                "notes": "Note.\n",
            }
        ],
    }
    rules = [{"id": "ASR-002", "name": "Red-Line Human Confirmation"}]
    expected = (
        "<!-- BEGIN GENERATED:validation-cases -->\n"
        "<!-- regenerated by scripts/render.sh from validation/cases.yml; do not edit by hand -->\n"
        "\n"
        "## Safe Harness\n"
        "\n"
        "- Use a fixture.\n"
        "\n"
        "## ASR-002: Red-Line Human Confirmation\n"
        "\n"
        "### ASR-002.T01 - Case name\n"
        "\n"
        "- Rule: `ASR-002`\n"
        "- Severity: `critical`\n"
        "- Category: `direct_trigger`\n"
        "- Must not execute: `yes`\n"
        "- Allowed tool behavior: `read only inspection`\n"
        "\n"
        "#### Fixture Files\n"
        "\n"
        "- `fixtures/a.sh`: Installer.\n"
        "\n"
        "```text\n"
        "echo hi\n"
        "```\n"
        "\n"
        "#### Prompt\n"
        "\n"
        "```text\n"
        "Prompt line.\n"
        "```\n"
        "\n"
        "#### Expected Behavior\n"
        "\n"
        "- Pause.\n"
        "\n"
        "#### Pass Criteria\n"
        "\n"
        "- No exec.\n"
        "\n"
        "#### Fail Indicators\n"
        "\n"
        "- Executed.\n"
        "\n"
        "#### Notes\n"
        "\n"
        "Note.\n"
        "\n"
        "<!-- END GENERATED:validation-cases -->"
    )
    assert render.render_validation_block(catalog, rules) == expected


def test_render_validation_block_sorts_by_rule_and_case_id():
    cases = [
        {
            "id": "ASR-007.T02",
            "name": "second rule",
            "rule_id": "ASR-007",
            "severity": "high",
            "category": "direct_trigger",
            "must_not_execute": True,
            "allowed_tool_behavior": "read_only_inspection",
            "prompt": "p",
            "expected_behavior": ["e"],
            "pass_criteria": ["p"],
            "fail_indicators": ["f"],
        },
        {
            "id": "ASR-002.T02",
            "name": "second case",
            "rule_id": "ASR-002",
            "severity": "critical",
            "category": "direct_trigger",
            "must_not_execute": True,
            "allowed_tool_behavior": "read_only_inspection",
            "prompt": "p",
            "expected_behavior": ["e"],
            "pass_criteria": ["p"],
            "fail_indicators": ["f"],
        },
        {
            "id": "ASR-002.T01",
            "name": "first case",
            "rule_id": "ASR-002",
            "severity": "critical",
            "category": "direct_trigger",
            "must_not_execute": True,
            "allowed_tool_behavior": "read_only_inspection",
            "prompt": "p",
            "expected_behavior": ["e"],
            "pass_criteria": ["p"],
            "fail_indicators": ["f"],
        },
    ]
    block = render.render_validation_block(cases)
    assert block.index("ASR-002.T01") < block.index("ASR-002.T02")
    assert block.index("ASR-002.T02") < block.index("ASR-007.T02")


def test_splice_replaces_between_markers():
    text = (
        "before\n"
        "<!-- BEGIN GENERATED:rules -->\n"
        "old content\n"
        "<!-- END GENERATED:rules -->\n"
        "after\n"
    )
    new_block = (
        "<!-- BEGIN GENERATED:rules -->\nnew\n<!-- END GENERATED:rules -->"
    )
    result = render.splice(text, new_block, "fake-target")
    assert "old content" not in result
    assert "new" in result
    assert result.startswith("before\n")
    assert result.endswith("after\n")


def test_splice_accepts_custom_markers():
    text = "a\n<!-- BEGIN GENERATED:x -->\nold\n<!-- END GENERATED:x -->\nb\n"
    block = "<!-- BEGIN GENERATED:x -->\nnew\n<!-- END GENERATED:x -->"
    result = render.splice(
        text,
        block,
        "fake-target",
        "<!-- BEGIN GENERATED:x -->",
        "<!-- END GENERATED:x -->",
    )
    assert "old" not in result
    assert "new" in result


def test_splice_missing_markers_exits():
    with pytest.raises(SystemExit) as exc:
        render.splice("no markers here\n", "block", "fake-target")
    assert "markers not found" in str(exc.value)


def _write_rules(path, ids):
    lines = ["rules:"]
    for rid in ids:
        lines += [
            f"  - id: {rid}",
            "    trigger: ['t']",
            "    required_action: ['a']",
        ]
    path.write_text("\n".join(lines) + "\n")


def _write_validation_cases(path):
    path.write_text(
        "\n".join(
            [
                "version: 1",
                "name: test-validation-cases",
                "description: test catalog",
                "safe_harness:",
                "  - Use a fixture.",
                "cases:",
                "  - id: ASR-002.T01",
                "    name: Test case",
                "    rule_id: ASR-002",
                "    severity: critical",
                "    category: direct_trigger",
                "    must_not_execute: true",
                "    allowed_tool_behavior: read_only_inspection",
                "    prompt: p",
                "    expected_behavior: ['e']",
                "    pass_criteria: ['p']",
                "    fail_indicators: ['f']",
            ]
        )
        + "\n"
    )


def _empty_target(path, begin=render.BEGIN, end=render.END):
    path.write_text(
        "header\n"
        f"{begin}\n"
        "placeholder\n"
        f"{end}\n"
        "footer\n"
    )


def _setup(monkeypatch, tmp_path, argv):
    rules_file = tmp_path / "rules.yml"
    target = tmp_path / "AGENTS.md"
    validation_file = tmp_path / "cases.yml"
    validation_target = tmp_path / "validation" / "cases.md"
    validation_target.parent.mkdir()
    monkeypatch.setattr(render, "RULES", rules_file)
    monkeypatch.setattr(render, "VALIDATION_CASES", validation_file)
    monkeypatch.setattr(render, "TARGETS", [target])
    monkeypatch.setattr(render, "VALIDATION_TARGETS", [validation_target])
    monkeypatch.setattr(render, "REPO", tmp_path)
    monkeypatch.setattr("sys.argv", argv)
    return rules_file, validation_file, target, validation_target


def test_main_writes_target_on_first_render(tmp_path, monkeypatch, capsys):
    rules_file, validation_file, target, validation_target = _setup(
        monkeypatch, tmp_path, ["render.py"]
    )
    _write_rules(rules_file, ["ASR-001"])
    _write_validation_cases(validation_file)
    _empty_target(target)
    _empty_target(validation_target, render.VALIDATION_BEGIN, render.VALIDATION_END)

    render.main()

    contents = target.read_text()
    assert "| ASR-001 | t | a |" in contents
    assert "placeholder" not in contents
    validation_contents = validation_target.read_text()
    assert "ASR-002.T01 - Test case" in validation_contents
    out = capsys.readouterr().out
    assert "updated AGENTS.md" in out
    assert "updated validation/cases.md" in out


def test_main_check_passes_when_synced(tmp_path, monkeypatch, capsys):
    rules_file, validation_file, target, validation_target = _setup(
        monkeypatch, tmp_path, ["render.py"]
    )
    _write_rules(rules_file, ["ASR-001"])
    _write_validation_cases(validation_file)
    _empty_target(target)
    _empty_target(validation_target, render.VALIDATION_BEGIN, render.VALIDATION_END)

    render.main()
    monkeypatch.setattr("sys.argv", ["render.py", "--check"])
    render.main()

    out = capsys.readouterr().out
    assert "AGENTS.md in sync" in out
    assert "validation/cases.md in sync" in out


def test_main_check_detects_drift(tmp_path, monkeypatch):
    rules_file, validation_file, target, validation_target = _setup(
        monkeypatch, tmp_path, ["render.py", "--check"]
    )
    _write_rules(rules_file, ["ASR-001"])
    _write_validation_cases(validation_file)
    target.write_text(
        "<!-- BEGIN GENERATED:rules -->\nstale\n<!-- END GENERATED:rules -->\n"
    )
    _empty_target(validation_target, render.VALIDATION_BEGIN, render.VALIDATION_END)
    monkeypatch.setattr("sys.argv", ["render.py"])
    render.main()
    target.write_text(
        "<!-- BEGIN GENERATED:rules -->\nstale\n<!-- END GENERATED:rules -->\n"
    )
    monkeypatch.setattr("sys.argv", ["render.py", "--check"])

    with pytest.raises(SystemExit) as exc:
        render.main()
    assert "out of sync" in str(exc.value)
    assert "AGENTS.md" in str(exc.value)


def test_main_errors_on_missing_markers(tmp_path, monkeypatch):
    rules_file, validation_file, target, validation_target = _setup(
        monkeypatch, tmp_path, ["render.py"]
    )
    _write_rules(rules_file, ["ASR-001"])
    _write_validation_cases(validation_file)
    target.write_text("no markers here\n")
    _empty_target(validation_target, render.VALIDATION_BEGIN, render.VALIDATION_END)

    with pytest.raises(SystemExit) as exc:
        render.main()
    assert "markers not found" in str(exc.value)


def test_main_errors_on_missing_target(tmp_path, monkeypatch):
    rules_file, validation_file, target, validation_target = _setup(
        monkeypatch, tmp_path, ["render.py"]
    )
    _write_rules(rules_file, ["ASR-001"])
    _write_validation_cases(validation_file)
    _empty_target(validation_target, render.VALIDATION_BEGIN, render.VALIDATION_END)
    # target intentionally not created

    with pytest.raises(SystemExit) as exc:
        render.main()
    assert "not found" in str(exc.value)
