import pytest

import render


def test_cell_joins_with_semicolon():
    assert render.cell(["a", "b", "c"]) == "a; b; c"


def test_cell_strips_whitespace():
    assert render.cell(["  a  ", " b"]) == "a; b"


def test_cell_single_item():
    assert render.cell(["only"]) == "only"


def test_render_block_golden():
    rules = [
        {
            "id": "ASR-001",
            "trigger": ["First trigger.", "Second trigger."],
            "required_action": ["Do X.", "Then Y."],
        },
    ]
    expected = (
        "<!-- BEGIN GENERATED:rules -->\n"
        "<!-- regenerated by scripts/render.sh from rules/agent-security-rules.yml; do not edit by hand -->\n"
        "\n"
        "| ID | Trigger | Required action |\n"
        "| --- | --- | --- |\n"
        "| ASR-001 | First trigger.; Second trigger. | Do X.; Then Y. |\n"
        "\n"
        "<!-- END GENERATED:rules -->"
    )
    assert render.render_block(rules) == expected


def test_render_block_sorts_by_id():
    rules = [
        {"id": "ASR-003", "trigger": ["t3"], "required_action": ["a3"]},
        {"id": "ASR-001", "trigger": ["t1"], "required_action": ["a1"]},
        {"id": "ASR-002", "trigger": ["t2"], "required_action": ["a2"]},
    ]
    block = render.render_block(rules)
    assert block.index("ASR-001") < block.index("ASR-002") < block.index("ASR-003")


def test_render_block_multi_item_joined_with_semicolon():
    rules = [
        {
            "id": "ASR-001",
            "trigger": ["one", "two"],
            "required_action": ["alpha", "beta", "gamma"],
        }
    ]
    block = render.render_block(rules)
    assert "| one; two |" in block
    assert "| alpha; beta; gamma |" in block


def test_render_block_idempotent():
    rules = [{"id": "ASR-001", "trigger": ["t"], "required_action": ["a"]}]
    assert render.render_block(rules) == render.render_block(rules)


def test_splice_replaces_between_markers():
    text = (
        "before\n"
        "<!-- BEGIN GENERATED:rules -->\n"
        "old content\n"
        "<!-- END GENERATED:rules -->\n"
        "after\n"
    )
    new_block = (
        "<!-- BEGIN GENERATED:rules -->\nnew\n<!-- END GENERATED:rules -->"
    )
    result = render.splice(text, new_block, "fake-target")
    assert "old content" not in result
    assert "new" in result
    assert result.startswith("before\n")
    assert result.endswith("after\n")


def test_splice_missing_markers_exits():
    with pytest.raises(SystemExit) as exc:
        render.splice("no markers here\n", "block", "fake-target")
    assert "markers not found" in str(exc.value)


def _write_rules(path, ids):
    lines = ["rules:"]
    for rid in ids:
        lines += [
            f"  - id: {rid}",
            "    trigger: ['t']",
            "    required_action: ['a']",
        ]
    path.write_text("\n".join(lines) + "\n")


def _empty_target(path):
    path.write_text(
        "header\n"
        "<!-- BEGIN GENERATED:rules -->\n"
        "placeholder\n"
        "<!-- END GENERATED:rules -->\n"
        "footer\n"
    )


def _setup(monkeypatch, tmp_path, argv):
    rules_file = tmp_path / "rules.yml"
    target = tmp_path / "AGENTS.md"
    monkeypatch.setattr(render, "RULES", rules_file)
    monkeypatch.setattr(render, "TARGETS", [target])
    monkeypatch.setattr(render, "REPO", tmp_path)
    monkeypatch.setattr("sys.argv", argv)
    return rules_file, target


def test_main_writes_target_on_first_render(tmp_path, monkeypatch, capsys):
    rules_file, target = _setup(monkeypatch, tmp_path, ["render.py"])
    _write_rules(rules_file, ["ASR-001"])
    _empty_target(target)

    render.main()

    contents = target.read_text()
    assert "| ASR-001 | t | a |" in contents
    assert "placeholder" not in contents
    assert "updated AGENTS.md" in capsys.readouterr().out


def test_main_check_passes_when_synced(tmp_path, monkeypatch, capsys):
    rules_file, target = _setup(monkeypatch, tmp_path, ["render.py"])
    _write_rules(rules_file, ["ASR-001"])
    _empty_target(target)

    render.main()
    monkeypatch.setattr("sys.argv", ["render.py", "--check"])
    render.main()

    assert "AGENTS.md in sync" in capsys.readouterr().out


def test_main_check_detects_drift(tmp_path, monkeypatch):
    rules_file, target = _setup(monkeypatch, tmp_path, ["render.py", "--check"])
    _write_rules(rules_file, ["ASR-001"])
    target.write_text(
        "<!-- BEGIN GENERATED:rules -->\nstale\n<!-- END GENERATED:rules -->\n"
    )

    with pytest.raises(SystemExit) as exc:
        render.main()
    assert "out of sync" in str(exc.value)
    assert "AGENTS.md" in str(exc.value)


def test_main_errors_on_missing_markers(tmp_path, monkeypatch):
    rules_file, target = _setup(monkeypatch, tmp_path, ["render.py"])
    _write_rules(rules_file, ["ASR-001"])
    target.write_text("no markers here\n")

    with pytest.raises(SystemExit) as exc:
        render.main()
    assert "markers not found" in str(exc.value)


def test_main_errors_on_missing_target(tmp_path, monkeypatch):
    rules_file, target = _setup(monkeypatch, tmp_path, ["render.py"])
    _write_rules(rules_file, ["ASR-001"])
    # target intentionally not created

    with pytest.raises(SystemExit) as exc:
        render.main()
    assert "not found" in str(exc.value)
