#!/usr/bin/env python3
"""Render generated Markdown blocks from structured security-policy sources."""

import argparse
from collections import defaultdict
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("error: PyYAML required (pip install pyyaml)")

REPO = Path(__file__).resolve().parent.parent
RULES = REPO / "rules" / "agent-security-rules.yml"
VALIDATION_CASES = REPO / "validation" / "cases.yml"
TARGETS = [REPO / "AGENTS.md", REPO / "CLAUDE.md"]
VALIDATION_TARGETS = [REPO / "validation" / "cases.md"]
BEGIN = "<!-- BEGIN GENERATED:rules -->"
END = "<!-- END GENERATED:rules -->"
VALIDATION_BEGIN = "<!-- BEGIN GENERATED:validation-cases -->"
VALIDATION_END = "<!-- END GENERATED:validation-cases -->"


def cell(items):
    return "; ".join(s.strip() for s in items)


def render_block(rules, begin=BEGIN, end=END):
    rows = ["| ID | Trigger | Required action |", "| --- | --- | --- |"]
    for r in sorted(rules, key=lambda r: r["id"]):
        rows.append(f"| {r['id']} | {cell(r['trigger'])} | {cell(r['required_action'])} |")
    table = "\n".join(rows)
    return (
        f"{begin}\n"
        "<!-- regenerated by scripts/render.sh from rules/agent-security-rules.yml; do not edit by hand -->\n\n"
        f"{table}\n\n"
        f"{end}"
    )


def bool_word(value):
    return "yes" if value else "no"


def display_tool_behavior(value):
    return value.replace("_", " ")


def indented_block(text):
    return text.rstrip().splitlines()


def bullet_section(lines, title, items):
    lines.append(f"#### {title}")
    lines.append("")
    for item in items:
        lines.append(f"- {item}")
    lines.append("")


def render_validation_block(catalog, rules=None, begin=VALIDATION_BEGIN, end=VALIDATION_END):
    if isinstance(catalog, dict):
        cases = catalog["cases"]
        safe_harness = catalog.get("safe_harness", [])
    else:
        cases = catalog
        safe_harness = []

    rule_names = {rule["id"]: rule.get("name", "") for rule in rules or []}
    grouped = defaultdict(list)
    for case in sorted(cases, key=lambda item: item["id"]):
        grouped[case["rule_id"]].append(case)

    lines = [
        begin,
        "<!-- regenerated by scripts/render.sh from validation/cases.yml; do not edit by hand -->",
        "",
    ]

    if safe_harness:
        lines.extend(["## Safe Harness", ""])
        for item in safe_harness:
            lines.append(f"- {item}")
        lines.append("")

    for rule_id in sorted(grouped):
        rule_name = rule_names.get(rule_id, "")
        title = f"{rule_id}: {rule_name}" if rule_name else rule_id
        lines.extend([f"## {title}", ""])

        for case in grouped[rule_id]:
            lines.extend(
                [
                    f"### {case['id']} - {case['name']}",
                    "",
                    f"- Rule: `{case['rule_id']}`",
                    f"- Severity: `{case['severity']}`",
                    f"- Category: `{case['category']}`",
                    f"- Must not execute: `{bool_word(case['must_not_execute'])}`",
                    f"- Allowed tool behavior: `{display_tool_behavior(case['allowed_tool_behavior'])}`",
                    "",
                ]
            )

            fixture_files = case.get("fixture_files", [])
            if fixture_files:
                lines.extend(["#### Fixture Files", ""])
                for fixture in fixture_files:
                    lines.append(f"- `{fixture['path']}`: {fixture['purpose']}")
                    lines.append("")
                    lines.append("```text")
                    lines.extend(indented_block(fixture["content"]))
                    lines.append("```")
                    lines.append("")

            lines.extend(["#### Prompt", "", "```text"])
            lines.extend(indented_block(case["prompt"]))
            lines.extend(["```", ""])

            bullet_section(lines, "Expected Behavior", case["expected_behavior"])
            bullet_section(lines, "Pass Criteria", case["pass_criteria"])
            bullet_section(lines, "Fail Indicators", case["fail_indicators"])

            notes = case.get("notes", "").strip()
            if notes:
                lines.extend(["#### Notes", "", notes, ""])

    lines.append(end)
    return "\n".join(lines)


def splice(text, block, target, begin=BEGIN, end=END):
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if not pat.search(text):
        sys.exit(f"error: markers not found in {target}")
    return pat.sub(block, text)


def load_yaml(path):
    return yaml.safe_load(path.read_text())


def render_jobs():
    rules_data = load_yaml(RULES)
    validation_data = load_yaml(VALIDATION_CASES)

    return [
        {
            "targets": TARGETS,
            "block": render_block(rules_data["rules"]),
            "begin": BEGIN,
            "end": END,
        },
        {
            "targets": VALIDATION_TARGETS,
            "block": render_validation_block(validation_data, rules_data["rules"]),
            "begin": VALIDATION_BEGIN,
            "end": VALIDATION_END,
        },
    ]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if any target is out of sync with the YAML",
    )
    args = ap.parse_args()

    out_of_sync = []
    for job in render_jobs():
        for target in job["targets"]:
            rel = target.relative_to(REPO)
            if not target.exists():
                sys.exit(f"error: {rel} not found")
            current = target.read_text()
            rendered = splice(current, job["block"], target, job["begin"], job["end"])

            if args.check:
                if current != rendered:
                    out_of_sync.append(str(rel))
                else:
                    print(f"{rel} in sync")
                continue

            if current != rendered:
                target.write_text(rendered)
                print(f"updated {rel}")
            else:
                print(f"{rel} unchanged")

    if args.check and out_of_sync:
        sys.exit("out of sync with generated sources: " + ", ".join(out_of_sync))


if __name__ == "__main__":
    main()
