#!/usr/bin/env python3
"""Render the security-rules block in AGENTS.md from rules/agent-security-rules.yml."""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("error: PyYAML required (pip install pyyaml)")

REPO = Path(__file__).resolve().parent.parent
RULES = REPO / "rules" / "agent-security-rules.yml"
TARGETS = [REPO / "AGENTS.md", REPO / "CLAUDE.md"]
BEGIN = "<!-- BEGIN GENERATED:rules -->"
END = "<!-- END GENERATED:rules -->"


def cell(items):
    return "; ".join(s.strip() for s in items)


def render_block(rules):
    rows = ["| ID | Trigger | Required action |", "| --- | --- | --- |"]
    for r in sorted(rules, key=lambda r: r["id"]):
        rows.append(f"| {r['id']} | {cell(r['trigger'])} | {cell(r['required_action'])} |")
    table = "\n".join(rows)
    return (
        f"{BEGIN}\n"
        "<!-- regenerated by scripts/render.sh from rules/agent-security-rules.yml; do not edit by hand -->\n\n"
        f"{table}\n\n"
        f"{END}"
    )


def splice(text, block, target):
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pat.search(text):
        sys.exit(f"error: markers not found in {target}")
    return pat.sub(block, text)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if any target is out of sync with the YAML",
    )
    args = ap.parse_args()

    data = yaml.safe_load(RULES.read_text())
    block = render_block(data["rules"])

    out_of_sync = []
    for target in TARGETS:
        rel = target.relative_to(REPO)
        if not target.exists():
            sys.exit(f"error: {rel} not found")
        current = target.read_text()
        rendered = splice(current, block, target)

        if args.check:
            if current != rendered:
                out_of_sync.append(str(rel))
            else:
                print(f"{rel} in sync")
            continue

        if current != rendered:
            target.write_text(rendered)
            print(f"updated {rel}")
        else:
            print(f"{rel} unchanged")

    if args.check and out_of_sync:
        sys.exit(
            "out of sync with rules/agent-security-rules.yml: " + ", ".join(out_of_sync)
        )


if __name__ == "__main__":
    main()
